### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by joegoldbeck** [joegoldbeck/wpb-bot#16]
- JSON logs
- Add info on the match that was made

(Possibly add that info to the posts_replied db (#15)  as well)

**Comment by Hucxley** [comment]
Added some info to posts_replied db for matches and mismatches [#22](https://github.com/joegoldbeck/wpb-bot/pull/22), and added replied: False category to posts_db so we can manually review false matches and update plans_db with new entries or explore synonym matching to improve results.

**Comment by Hucxley** [comment]
Logs in Firestore seem fairly complete at this time.  Additional metadata that may be needed will likely arise during development, refactoring, or scoring methodology modifications as appropriate.
