### ISSUE TITLE
Responses when multiple plans are highly reasonable matches

### ISSUE THREAD

**Issue by joegoldbeck** [joegoldbeck/wpb-bot#45]
Some queries don't have a specific plan associated, but have _many_ plans associated with them

For example, "climate change" could match any of the following plans 
```
[
      "new_farm_economy",
      "national_security_climate_change",
      "green_manufacturing",
      "climate_risk_disclosure"
    ]
```

Or "fair pay" could reasonably match `economic_patriotism` or `women_of_color_economic`

In these cases, instead of just picking one, we might want to return a few, or perhaps highlight one top plan (including the summary), but then also include other links that may be relevant.

**Comment by Hucxley** [comment]
I think responding with the hyperlinked display title all of plans above the threshold would be a better idea, and let users choose what they're looking for.
