### ISSUE TITLE
Show me the plans

### ISSUE THREAD

**Issue by joegoldbeck** [joegoldbeck/wpb-bot#72]
!WarrenPlanBot show me the plans

Should show all the plans.

We should also include a pointer to this command we don't have matches

ex of how to make it all in a table nicely
| Ticker | Investment | Profit |
|--------|------------|--------|
| BTC    | $100       | $-50   |
| ETH    | $1000      | $-500  |
| DOGE   | $10000     | $-5000 |

**Comment by Hucxley** [comment]
closed with #76
