### ISSUE TITLE
Add Trade Plan from July 29th

### ISSUE THREAD

**Issue by Hucxley** [joegoldbeck/wpb-bot#83]
Missed this one:
 - https://medium.com/@teamwarren/trade-on-our-terms-ad861879feca

**Comment by joegoldbeck** [comment]
How do you generate the summaries? Are those by hand or the first paragraph or...?

**Comment by Hucxley** [comment]
Usually it's what's on the issues page of the website, or if it's not on
the issues page, the first or last two paragraphs of the article are often
good sources to find a summary of the proposal.
