### ISSUE TITLE
WPB failed on a response to Medicare for All

### ISSUE THREAD

**Issue by Hucxley** [joegoldbeck/wpb-bot#89]
https://www.reddit.com/r/ElizabethWarren/comments/cvo7r4/weekly_update_and_discussion_thread_826_to_91/eyuo58y/

Check the replies. It responded with the tribal health plan.

Need to find Warren's support for Bernie's M4A bill and put it in the labeled responses until she comes out with a specific policy plan about Medicare For All.

**Comment by joegoldbeck** [comment]
Didn’t it reply with “idk”? I don’t think it matched a plan, let alone tribal health plan :)

**Comment by Hucxley** [comment]
I linked the wrong post initially. Check the issue edit.

**Comment by joegoldbeck** [comment]
Closes by #90
